
import { PromptRecord, DB_CONFIG } from '../types';

const HEADERS = {
    'apikey': DB_CONFIG.KEY,
    'Authorization': `Bearer ${DB_CONFIG.KEY}`,
    'Content-Type': 'application/json',
    'Prefer': 'return=representation'
};

export const DbService = {
    async testConnection(): Promise<boolean> {
        try {
            const res = await fetch(`${DB_CONFIG.URL}/rest/v1/prompts?select=count`, {
                method: 'GET',
                headers: {
                    'apikey': DB_CONFIG.KEY,
                    'Authorization': `Bearer ${DB_CONFIG.KEY}`,
                }
            });
            return res.ok;
        } catch (e) {
            console.error("DB Connection failed", e);
            return false;
        }
    },

    async getAllPrompts(): Promise<PromptRecord[]> {
        const res = await fetch(`${DB_CONFIG.URL}/rest/v1/prompts?select=*&order=created_at.desc`, {
            headers: HEADERS
        });
        if (!res.ok) throw new Error('Failed to fetch prompts');
        return await res.json();
    },

    async createPrompt(record: Omit<PromptRecord, 'id' | 'created_at'>): Promise<PromptRecord> {
        const res = await fetch(`${DB_CONFIG.URL}/rest/v1/prompts`, {
            method: 'POST',
            headers: HEADERS,
            body: JSON.stringify(record)
        });
        if (!res.ok) throw new Error('Failed to create prompt');
        const data = await res.json();
        return data[0];
    },

    async updatePrompt(id: number, record: Partial<PromptRecord>): Promise<PromptRecord> {
        const res = await fetch(`${DB_CONFIG.URL}/rest/v1/prompts?id=eq.${id}`, {
            method: 'PATCH',
            headers: HEADERS,
            body: JSON.stringify(record)
        });
        if (!res.ok) throw new Error('Failed to update prompt');
        const data = await res.json();
        return data[0];
    },

    async deletePrompt(id: number): Promise<void> {
        const res = await fetch(`${DB_CONFIG.URL}/rest/v1/prompts?id=eq.${id}`, {
            method: 'DELETE',
            headers: HEADERS
        });
        if (!res.ok) throw new Error('Failed to delete prompt');
    },

    getSQLSchema(): string {
        return `
-- Please run this in your Supabase SQL Editor
create table if not exists prompts (
  id bigint generated by default as identity primary key,
  title text not null,
  summary text,
  content text,
  excontext text,
  version text default 'v1.0',
  created_at timestamp with time zone default timezone('utc'::text, now())
);
        `.trim();
    }
};
